@ACCESS_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImhPdndzb0N5S3FXaXNwcGNrMUgxRiJ9.eyJpc3MiOiJodHRwczovL2Rldi16aGd5ZnJobWs2NTd1YXR4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NWRiZjhiYTQyYmRhMGFhZTMzNTdkZGEiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDozMDAwLyoiLCJodHRwczovL2Rldi16aGd5ZnJobWs2NTd1YXR4LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MDk4MDg3NTcsImV4cCI6MTcwOTg5NTE1NywiYXpwIjoic3RSU1FOM2ZtQ0FGcnVpVm5UT1JWMGJHbGNMV1pOZ2MiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.vMQavtWwpyhgpGXbj6GtXfry2KgmyDUFjMKse5xB6slbQZFoTmCXIZJ12MgXKzDebhdjHtlhSuqbz-kuVRXtJ0px7LoogFrbf_0FfdoIHI_B5xXo9lTAOMNN0Zv1reDuMrMqras-yApCZdol6O-8lZof9H9GVQGBuIVKXblsG5CTyQiT6NBN69NIESIDBJPOpzZCXH5duMObDeklL2zVLJNYX8IYiPOB9oJKu_Rl9MligN88FATyCBXBPwxDHzpF4MXMeXIJRV_ZcbV8cnEWTfPMr1bKCJhDdWSxy8k0IJOXLUEFm-hmlnewyWutL4pZDsgGb024BhS3A9ID37siZg

GET https://dev-zhgyfrhmk657uatx.us.auth0.com/userinfo
Authorization: Bearer {{ACCESS_TOKEN}}

###

POST http://localhost:3000/api/transactions/add
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "type": "expense",
    "amount": 500,
    "note": "random super stuff"
}