@ACCESS_TOKEN=

GET https://dev-zhgyfrhmk657uatx.us.auth0.com/userinfo
Authorization: Bearer {{ACCESS_TOKEN}}

###

POST http://localhost:3000/api/transactions/add
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "type": "expense",
    "amount": 500,
    "note": "random super stuff"
}