@ACCESS_TOKEN=

GET https://dev-zhgyfrhmk657uatx.us.auth0.com/userinfo
Authorization: Bearer {{ACCESS_TOKEN}}

###

GET http://localhost:3000/api/transactions/list?type=income
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

